### ISSUE TITLE
Test timeouts after test script exits cleanly

### ISSUE THREAD

**Issue by mheon** [jlebon/redhat-ci#101]
Example log: https://s3.amazonaws.com/aos-ci/ghprb/containers/libpod/87d239ae21bbb50ff019b68076ef59f3fd7f5fbb.1.1536245660916850646/output.log

In the libpod repo, we're seeing a lot of tests (I'd estimate around 25+% of all our test runs) failing with timeouts after the actual test script exits cleanly. In the linked log, the test script exits at the second-to-last line cleanly with the exit 0. However, the test subsequently times out and is flagged as failed/exit 1 in papr.

**Comment by mheon** [comment]
@jwhonce has seen this one a lot on his PRs

**Comment by jlebon** [comment]
Hmm, I'm trying to reproduce this on the latest Fedora Atomic Host release, but I hit test failures:

```
Summarizing 6 Failures:

[Fail] Podman logs [It] podman logs tail two lines
/go/src/github.com/containers/libpod/test/e2e/logs_test.go:58

[Fail] Podman logs [It] podman logs tail two lines
/go/src/github.com/containers/libpod/test/e2e/logs_test.go:58

[Fail] Podman logs [It] podman logs tail two lines
/go/src/github.com/containers/libpod/test/e2e/logs_test.go:58

[Fail] Podman logs [It] podman logs tail 2 lines with timestamps
/go/src/github.com/containers/libpod/test/e2e/logs_test.go:84

[Fail] Podman logs [It] podman logs tail 2 lines with timestamps
/go/src/github.com/containers/libpod/test/e2e/logs_test.go:84

[Fail] Podman logs [It] podman logs tail 2 lines with timestamps
/go/src/github.com/containers/libpod/test/e2e/logs_test.go:84

Ran 428 of 442 Specs in 755.525 seconds
FAIL! -- 426 Passed | 2 Failed | 0 Flaked | 0 Pending | 14 Skipped
--- FAIL: TestLibpod (755.53s)
FAIL
coverage: 0.0% of statements

Ginkgo ran 1 suite in 12m49.663295745s
Test Suite Failed
```

> failing with timeouts after the actual test script exits cleanly

It might be timeouts, but it's not PAPR that's cutting it off. The message at the bottom when a test times out is different: https://github.com/projectatomic/papr/blob/2239c83d5de88fbff8fe99e8845cffd26a18f3f3/papr/testrunner#L450

Looking more closely now, that `exit 0` at the end comes from: https://github.com/containers/libpod/blob/f0c962282b634b5103952b2130addbc71413d0f4/.papr.sh#L34. But that script is spawned by https://github.com/containers/libpod/blob/f0c962282b634b5103952b2130addbc71413d0f4/.papr_prepare.sh#L17.

Might be worth changing it to something like this:

```sh
rc=0
${CONTAINER_RUNTIME} run ... || rc=$?
if [ $rc != 0 ]; then
  echo "${CONTAINER_RUNTIME} run returned $rc!"
  journalctl --no-pager > journal.log
  exit 1
fi
```

And then add `journal.log` to your artifacts and see if there's anything interesting in there.

**Comment by mheon** [comment]
@jlebon After added that (https://github.com/containers/libpod/pull/1439) I'm not seeing any journal.log artifacts being generated. This seems to me to indicate that the container runtime is exiting cleanly?

**Comment by jlebon** [comment]
Are we OK to close this one now?

**Comment by mheon** [comment]
@jlebon I think so - I'll reopen with more details if we start seeing this again
