### ISSUE TITLE
save PR status on auto branch when it fails

### ISSUE THREAD

**Issue by cgwalters** [jlebon/redhat-ci#23]
If we are using multiple required statuses, currently redhat-ci links back to the auto branch, but that can get overwritten.

An example is https://github.com/projectatomic/atomic/pull/886

Unfortunately AFAICS, there's no *web* link for the status of a commit, if I click directly on https://github.com/projectatomic/atomic/commit/fe375675562aaf3a4f0e616c2216c3ba92aa4ab4 it doesn't show me the status.

So...I'm not sure.  We could obviously gather this info ourself and put it in a S3 bucket?

**Comment by jlebon** [comment]
Yeah, that makes sense. I'll whip something up. Time to learn some more Jinja2. :)

**Comment by jlebon** [comment]
Fix for this is in #24.
