### ISSUE TITLE
PR testing doesn't happen if the message bus is down

### ISSUE THREAD

**Issue by cgwalters** [jlebon/redhat-ci#33]
https://github.com/projectatomic/rpm-ostree/pull/709 was pushed a while ago, but no PR status.

**Comment by cgwalters** [comment]
Currently @jlebon thinks this is the internal Jenkins getting hung up, and we don't have access to debug/restart it.

**Comment by jlebon** [comment]
The internal message bus is currently down. I filed a ticket to have it investigated. There is only a single point through the event flow at which we still rely on the message bus rather than using it as an optimization with polling fallback. Will work to change that.

**Comment by jlebon** [comment]
Actually, `auto` branches should still be getting polled and tested. So we should see https://github.com/projectatomic/atomic/pull/966 go through normally.

**Comment by jlebon** [comment]
(This is not specific to auto branches, just any branch test in general).

**Comment by jlebon** [comment]
Note that you should still be able to manually trigger a PR test by starting a build of the `github-ci-testers-executor` job and filling in the GitHub repo and pull id.

**Comment by jlebon** [comment]
This should be resolved now.

> There is only a single point through the event flow at which we still rely on the message bus rather than using it as an optimization with polling fallback. Will work to change that.

Let's use this card to track this work.

**Comment by jlebon** [comment]
This should be fixed now. In the event of the message bus going down, PRs should still be tested within 5 mins.
