### ISSUE TITLE
tests: aren't shell

### ISSUE THREAD

**Issue by cgwalters** [jlebon/redhat-ci#37]
I recently had to do https://github.com/ostreedev/ostree/pull/837/commits/0f38379bc5f981240b84f975df45fbb3660358b3
which took me a while to understand, because right now we don't log the output.

I'm not sure if we should change this, but it'd be worth documenting somewhere.

**Comment by jlebon** [comment]
Hmm, weird. Seems to work alright here. The strings in `tests` are pasted verbatim in a script file and executed as is.

Can you describe what you witnessed? I *think* this is the associated test output for the commit before the fixup you linked to here: https://s3.amazonaws.com/aos-ci/ghprb/ostreedev/ostree/8db0da1ada7124ad083c58a0c3b6dcc04cd44109.0.1494259940759140280/output.log

There, I see:

```
>>> gnome-desktop-testing-runner -p 0 --timeout $((10 * 60)) libostree/
Running test: libostree/test-help.sh.test
Running test: libostree/test-pull-c.test
Running test: libostree/test-bsdiff.test
...
```

That looks good!

Oh I see, are you referring to `$((10 * 60))` seemingly being passed literally? That might just be the way the commands are logged fooling you. E.g. see: https://s3.amazonaws.com/aos-ci/ghprb/jlebon/redhat-ci-sandbox/6d9d6d1d505ec83c9fbf8740e44fc82f42bb7af6.0.1494358165425304685/output.log

```
>>> echo $((10 * 60))
600
### COMPLETED IN 0s
```

**Comment by cgwalters** [comment]
Hm, yes may have been a thinko.
