### ISSUE TITLE
Naming of the project and definition file

### ISSUE THREAD

**Issue by gbraad** [jlebon/redhat-ci#5]
I noticed a `.redhat-ci.yml` file in the repository of commissaire. After searching I ended up here. I am a little confused about the name, as it suggest this to be an internal system for Red Hat to perform CI/CD builds. It is actually more related to Atomic and a public effort.

Note: was unable to find a public announcement of this project.

**Comment by jlebon** [comment]
> After searching I ended up here. I am a little confused about the name, as it suggest this to be an internal system for Red Hat to perform CI/CD builds. It is actually more related to Atomic and a public effort.

It's a bit of both actually. :) The backend Jenkins and OpenStack instances that run the builds are internal, but all the interesting logic lives here. The goal is to make it easier for folks to contribute, though it's a bit cumbersome to drive right now if you don't have Jenkins or OpenStack available on hand. I'll have to tweak the `README.md` to provide more info.

> Note: was unable to find a public announcement of this project.

This will probably happen once this repo gets transferred under the Project Atomic banner (it's still in beta mode for now).

**Comment by gbraad** [comment]
Thanks for the feedback. I hope it will become something more general... Might try it out later.

Cheers
