### ISSUE TITLE
queuing and multi-backend

### ISSUE THREAD

**Issue by cgwalters** [jlebon/redhat-ci#60]
The way the Cockpit CI works, workers in multiple distinct infrastructures poll github and try to opportunistically run suites.  One advantage of this is that github is the only central point of failure, and further github itself holds the queue of work to do.

In contrast today PAPR effectively replicates that queue into Jenkins.  There are advantages to this, but we're not really making much use of the availability of Jenkins scheduling; we just try to provision in OpenStack or on slaves directly.

Furthermore, particularly with Homu some tasks are more important than others - we need to prioritize tests for Homu merges over per-PR CI.

I think we need to explicitly recognize this queue in a similar way to homu.  This is also very similar to [Kubernetes Prow](http://prow.k8s.io/) which is now in use by [OpenShift Origin](https://origin-sq-status-ci.svc.ci.openshift.org/#/queue) as well.  Further I think this queue should be publicly visible like the Origin/Kube etc. ones are.

**Comment by cgwalters** [comment]
If our work queue was public, we could change things so that, like cockpit, any corporate internal resources (e.g. OpenStack) could poll for work too.

**Comment by jlebon** [comment]
That makes a lot of sense. One thing to note with PAPR today is that it's essentially a "one-shot" architecture. There are no long-running services; events from Jenkins cause new invocations to be run. This makes it very limited, but at the same time, it means that we can replace Jenkins with basically any other Service That Runs Stuff When Other Stuff Happens. We should definitely take a look at some of the projects that exist already for this before implementing our own. For one thing, I'm not very good at styling web pages, as the PAPR results pages show. :)

**Comment by cgwalters** [comment]
Closing as dup of https://github.com/projectatomic/papr/issues/62
