### ISSUE TITLE
Specs for cluster

### ISSUE THREAD

**Issue by ashcrow** [jlebon/redhat-ci#63]
In https://github.com/openshift/openshift-ansible/pull/5461 it looks like the hosts in ``cluster`` are running out of resources. The ``host`` directive has a ``specs`` section but it doesn't look like the ``cluster`` has anything similar. It would be awesome to have the ability to define something similar to ``specs`` at the cluster level.

[Example](https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/6a96bdfbc2fd9f22369f9b045c76007ec8cfe440.0.1506457777027466470/artifacts/journals/ocp-master.log)

```
Sep 26 20:37:49 ocp-master systemd[1]: systemd-coredump@1-8237-0.service: Failed to fork: Cannot allocate memory
Sep 26 20:37:49 ocp-master systemd[1]: systemd-coredump@1-8237-0.service: Failed to run 'start' task: Cannot allocate memory
```

**Comment by jlebon** [comment]
Yup, all the same keys as `host` are supported, including `specs`.
See: https://github.com/projectatomic/papr/pull/64.

**Comment by ashcrow** [comment]
@jlebon awesome, thanks!!
