### ISSUE TITLE
Questions about running papr locally

### ISSUE THREAD

**Issue by peterbaouoft** [jlebon/redhat-ci#95]
Hi,
I was following the https://github.com/projectatomic/papr/blob/ocp/docs/RUNNING.md, and got the following two errors when trying `pip install -r requirement.txt`

1: 
```
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  error: command 'gcc' failed with exit status 1
```
2: 
```
 unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
```

I fixed those by install gcc and redhat-rpm-config. Is that the expected behavior to have?

I also have another question. :-) I tried running the papr command as suggested from `RUNNING.md`, but failed with the following error. Any suggestions for how to fix it, or did I happen to have the wrong command? Thanks :)

```
(myenv) [root@localhost papr]# papr --debug runtest --conf docs/local.yaml --repo jlebon/papr-sandbox --branch dev
++ dirname /root/papr/papr/main
+ THIS_DIR=/root/papr/papr
+ source /root/papr/papr/utils/common.sh
+ main /root/myenv/bin/papr
+ rm -rf state
+ mkdir state
+ ensure_err_github_update
+ trap 'common_update_github '\''Red Hat CI'\'' error '\''An internal error occurred.'\''' ERR
+ validate_vars
+ '[' -n '' ']'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ echo 'ERROR: One of github_branch or github_pull_id must be specified.'
ERROR: One of github_branch or github_pull_id must be specified.
(myenv) [root@localhost papr]# oc status             
In project My Project (myproject) on server https://127.0.0.1:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.
```

**Comment by jlebon** [comment]
> I fixed those by install gcc and redhat-rpm-config. Is that the expected behavior to have?

Yup, that makes sense. Some Python packages have C components that get compiled at install time. 

>  I tried running the papr command as suggested from RUNNING.md, but failed with the following error

Ahh, it looks like you're on the `master` branch. You'll want to be on the `ocp` branch instead. :)

**Comment by peterbaouoft** [comment]
> Ahh, it looks like you're on the master branch. You'll want to be on the ocp branch instead

To confirm, the ocp branch is for local, and not for jenkins pipeline by any chance right? Will it(ocp branch) be worth mentioning in the `RUNNING.MD` file ;)? 

===================================Trial # 2 ==============================
I might of miss the instructions when reading, I recreated virtualenv and pip installed files, but now there seems to be a new error :p. 

```
(myenv) [root@localhost papr]# git branch
  master
* ocp

(myenv) [root@localhost papr]# papr --debug runtest --conf docs/local.yaml --repo jlebon/papr-sandbox --branch dev
DEBUG:main.py:31:main - debug logging turned on
Traceback (most recent call last):
  File "/root/myenv/bin/papr", line 11, in <module>
    load_entry_point('papr', 'console_scripts', 'papr')()
  File "/root/papr/papr/main.py", line 35, in main
    return args.func(args)
  File "/root/papr/papr/cmd_runtest.py", line 34, in _cmd_runtest
    site.init(args.conf)
  File "/root/papr/papr/site.py", line 25, in init
    _init_config()
  File "/root/papr/papr/site.py", line 39, in _init_config
    yaml.SafeLoader = yaml.CSafeLoader
AttributeError: module 'yaml' has no attribute 'CSafeLoader'
```

**Comment by jlebon** [comment]
You'll want to use the `ocp` branch for both local testing and if setting up the whole PACI pipeline. That's why the `RUNNING.md` is on the `ocp` branch. :)

> I might of miss the instructions when reading, I recreated virtualenv and pip installed files, but now there seems to be a new error :p.

Right, `RUNNING.md` has a paragraph about this:

> Note that we use the C implementation of PyYAML. Make sure to have libyaml-devel installed before running pip so that the PyYAML package is aware of it during its setup. If the PyYAML package is already cached, pip will not run its setup again, so you'll want to use `--no-cache-dir`.

So try installing `libyaml-devel` and rerunning with `--no-cache-dir`.

**Comment by peterbaouoft** [comment]
>You'll want to use the ocp branch for both local testing and if setting up the whole PACI pipeline. That's why the RUNNING.md is on the ocp branch. :)

WOT, did not even notice. That's why I missed it, /me always thought RUNNING.md was on the master branch :p. 

> So try installing libyaml-devel and rerunning with --no-cache-dir.

Ah oops, I did install libyaml-devel but did not rerun with --no-cache-dir. Now the problem disappears and the test runs properly locally :). 

Will close this issue and thanks for the help!
